# Linear algebra assignment week 7, day 4

In [7]:
import numpy as np

#define matrices
A = np.matrix([[1,2],[3,5]])
B = np.matrix([[1],[2]])

# find the inverse of A
A_inverse = np.linalg.inv(A)

# Solving for X
X =A_inverse * B
print(X)

[[-1.]
 [ 1.]]


In [8]:
#define matrices
A = np.matrix([[4,3],[1,1]])
B = np.matrix([[5],[2]])

# find the inverse of A
A_inverse = np.linalg.inv(A)

# Solving for X
X =A_inverse * B
print(X)

[[-1.]
 [ 3.]]


In [9]:
#define matrices
A = np.matrix([[4,3],[5,-9]])
B = np.matrix([[20],[26]])

# find the inverse of A
A_inverse = np.linalg.inv(A)

# Solving for X
X =A_inverse * B
print(X)

[[ 5.05882353]
 [-0.07843137]]


In [10]:
#define matrices
A = np.matrix([[4,1,3],[2,2,3],[3,5,2]])
B = np.matrix([[25],[-10],[-4]])

# find the inverse of A
A_inverse = np.linalg.inv(A)

# Solving for X
X =A_inverse * B
print(X)

[[14.55555556]
 [-5.88888889]
 [-9.11111111]]
